import io
import tempfile
from pathlib import Path

import cv2
import torch
from fastapi import FastAPI, File, UploadFile, HTTPException
from fastapi.staticfiles import StaticFiles
from PIL import Image
from torchvision import models, transforms
from ultralytics import YOLO

app = FastAPI()

model = models.resnet18(weights = None)
model.fc = torch.nn.Linear(model.fc.in_features, 2)
model.load_state_dict(torch.load("oil_model.pth", map_location='cpu', weights_only=True))

model.eval()

classes = ["no_oil","oil"]

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.Grayscale(num_output_channels=3),
    transforms.ToTensor(),
    transforms.Normalize([0.5,0.5,0.5], [0.5,0.5,0.5])
])



@app.post("/predict")
async def predict(file: UploadFile = File(...)):
    contents = await file.read()
    image = Image.open(io.BytesIO(contents)).convert('RGB')

    image = transform(image).unsqueeze(0)

    with torch.no_grad():
        outputs = model(image)
        _, pred = torch.max(outputs, 1)

    return {
        "prediction": classes[pred.item()]
    }


def convert_avi_to_mp4(input_path: Path, output_path: Path):
    cap = cv2.VideoCapture(str(input_path))
    if not cap.isOpened():
        raise Exception(f"Failed to open input video: {input_path}")

    fps = cap.get(cv2.CAP_PROP_FPS) or 30.0
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    # Use 'avc1' (H.264) codec
    fourcc = cv2.VideoWriter_fourcc(*'avc1')
    out = cv2.VideoWriter(str(output_path), fourcc, fps, (width, height))

    if not out.isOpened():
        fourcc = cv2.VideoWriter_fourcc(*'mp4v')
        out = cv2.VideoWriter(str(output_path), fourcc, fps, (width, height))

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break
        out.write(frame)

    cap.release()
    out.release()


@app.post("/video-detect")
async def video_detect(file: UploadFile = File(...)):
    if not file.filename:
        raise HTTPException(status_code=400, detail="No file uploaded")

    uploads_dir = Path("uploads")
    outputs_dir = Path("outputs/videos")
    uploads_dir.mkdir(exist_ok=True)
    outputs_dir.mkdir(exist_ok=True)

    suffix = Path(file.filename).suffix or ".mp4"
    temp_input_path = Path(tempfile.NamedTemporaryFile(dir=uploads_dir, suffix=suffix, delete=False).name)

    try:
        contents = await file.read()
        temp_input_path.write_bytes(contents)

        yolo_model = YOLO("models/best.pt")
        yolo_model.predict(
            source=str(temp_input_path),
            save=True,
            save_dir=str(outputs_dir.resolve()),
            exist_ok=True,
        )

        generated_video = None
        if outputs_dir.exists():
            video_extensions = {".mp4", ".avi", ".mov", ".mkv"}
            generated_video = max(
                (p for p in outputs_dir.iterdir() if p.is_file() and p.suffix.lower() in video_extensions),
                key=lambda p: p.stat().st_mtime,
                default=None,
            )

        if generated_video is None:
            raise HTTPException(status_code=500, detail="No video output was generated by YOLO")

        if generated_video.suffix.lower() != ".mp4":
            mp4_path = generated_video.with_suffix(".mp4")
            try:
                convert_avi_to_mp4(generated_video, mp4_path)
                generated_video.unlink(missing_ok=True)
                generated_video = mp4_path
            except Exception as e:
                print(f"Failed to convert video: {e}")

        return {
            "status": "success",
            "video_path": str(generated_video)
        }
    finally:
        if temp_input_path.exists():
            temp_input_path.unlink(missing_ok=True)


app.mount("/outputs", StaticFiles(directory="outputs"), name="outputs")
app.mount("/", StaticFiles(directory="frontend", html=True), name="frontend")